### ISSUE TITLE
Publish a snap package

### ISSUE THREAD

**Issue by j0npulsifer** [Shopify/ejson2env#16]
Related to https://github.com/Shopify/ejson2env/issues/7

Ref https://snapcraft.io/first-snap/golang

We should publish this as a snap such that we can `snap install ejson2env`. Travis can probably do the thing for us.

Here's the `snapcraft.yaml` that I used to build this in a pinch:

```yaml
name: ejson2env
version: '1.0'
summary: ejson2env is based on the ejson library and extends the ejson file format.
description: |
  ejson2env is a tool to simplify storing secrets that should be accessible in the shell environment in your git repo.
confinement: devmode
base: core18
parts:
  ejson2env:
    plugin: go
    go-importpath: github.com/Shopify/ejson2env
    source: https://github.com/Shopify/ejson2env
    source-type: git
apps:
  ejson2env:
    command: bin/ejson2env
```

![image](https://user-images.githubusercontent.com/22780844/79154991-75083b80-7d9e-11ea-8398-3fccc22284ca.png)
